config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#welcome'

  devise_for :users, controllers: {registrations: 'registrations'}
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :users do
    resource :avatar, only: %i[edit update]
    resources :profiles, only: %i[show edit update]
  end

  resources :villages do
    member do
      get 'start'
      get 'ruin'
    end
    resource :kick, only: %i[edit update], module: "villages"
    resources :rooms, only: [:show]
  end
  namespace :api, format: 'json' do
    namespace :v1 do
      resources :records, only: [:show] do
        member do
          put 'vote'
          put 'attack'
          put 'divine'
          put 'guard'
        end
      end
      resources :villages, only: [:show] do
        member do
          get 'remaining_time'
          get 'divine'
          get 'see_soul'
        end
      end
      resources :rooms, only: [:show] do
        member do
          get 'posts'
          get 'all_posts'
        end
      end
    end
  end

  resources :notifications
  resources :manuals, only: %i[show new edit create update destroy]
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['AWS_BUCKET']}/sitemaps/sitemap.xml.gz")

  resources :players, only: %i[new edit create update destroy] do
    resource :avatar, only: %i[edit update], module: "players"
  end
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Notification < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_notification, only: %i[show edit update destroy]
  before_action :authorize_notification

  def index
    @notifications = Notification.all.order("created_at DESC")
    @notifications = @notifications.page params[:page]
  end

  def show
  end

  def new
    @notification = Notification.new
  end

  def edit
  end

  def create
    @notification = Notification.new(notification_params)

    if @notification.save
      redirect_to @notification, notice: 'お知らせを作成しました'
    else
      render :new
    end
  end

  def update
    if @notification.update(notification_params)
      redirect_to @notification, notice: 'お知らせを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @notification.destroy
    redirect_to notifications_path, notice: 'お知らせを削除しました'
  end

  private

  def set_notification
    @notification = Notification.find(params[:id])
  end

  def authorize_notification
    authorize Notification
  end

  def notification_params
    params.require(:notification).permit(:title, :content)
  end
end

app/views/notifications/_form.html.slim
= form_for @notification do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control manual-content'
  - if @notification.persisted?
    .actions = f.submit "更新", class: 'btn btn-primary'
  - else
    .actions = f.submit "作成", class: 'btn btn-primary'

app/views/notifications/edit.html.slim
h1 お知らせの更新

== render 'form'

app/views/notifications/index.html.slim
- @page_title = 'お知らせ'
.notification-header
  - if policy(Notification).create?
    .pull-right.create-notification-button
      = button_to "新規作成", new_notification_path, method: :get, class: 'btn btn-sm btn-primary'
  h1 お知らせ

table class="table table-striped"
  thead
    tr
      th タイトル
      th 投稿日時

  tbody
    - @notifications.each do |notification|
      tr
        td
          = link_to(notification.title, notification_path(notification))
        td = datetime_display(notification.created_at)
= paginate @notifications

app/views/notifications/new.html.slim
h1 お知らせの作成

== render 'form'

app/views/notifications/show.html.slim
- @page_title = @notification.title
h1 = @notification.title
= markdown(@notification.content)

br
- if policy(Notification).update?
  = button_to '編集', edit_notification_path(@notification), method: :get, class: 'btn btn-primary'
  br
- if policy(Notification).destroy?
  = button_to '削除', @notification, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-danger'