config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#welcome'

  devise_for :users, controllers: {registrations: 'registrations'}
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :users do
    resource :avatar, only: %i[edit update]
    resources :profiles, only: %i[show edit update]
  end

  resources :villages do
    member do
      get 'start'
      get 'ruin'
    end
    resource :kick, only: %i[edit update], module: "villages"
    resources :rooms, only: [:show]
  end
  namespace :api, format: 'json' do
    namespace :v1 do
      resources :records, only: [:show] do
        member do
          put 'vote'
          put 'attack'
          put 'divine'
          put 'guard'
        end
      end
      resources :villages, only: [:show] do
        member do
          get 'remaining_time'
          get 'divine'
          get 'see_soul'
        end
      end
      resources :rooms, only: [:show] do
        member do
          get 'posts'
          get 'all_posts'
        end
      end
    end
  end

  resources :notifications
  resources :manuals, only: %i[show new edit create update destroy]
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['AWS_BUCKET']}/sitemaps/sitemap.xml.gz")

  resources :players, only: %i[new edit create update destroy] do
    resource :avatar, only: %i[edit update], module: "players"
  end
end

app/models/village.rb
# == Schema Information
#
# Table name: villages
#
#  id               :integer          not null, primary key
#  user_id          :integer          not null
#  name             :string           not null
#  player_num       :integer          not null
#  day              :integer          default(0), not null
#  next_update_time :datetime
#  discussion_time  :integer          not null
#  status           :integer          default("not_started"), not null
#  winner           :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  start_at         :datetime
#  show_vote_target :boolean          default(TRUE), not null
#  access_password  :string
#

class Village < ApplicationRecord
  after_create :create_rooms

  enum status: {
    not_started: 0,
    in_play: 1,
    ended: 2,
    ruined: 3
  }

  enum winner: {
    human_win: 0,
    werewolf_win: 1
  }

  belongs_to :user
  has_many :rooms, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :records
  has_many :results
  has_many :blacklist_users

  validates :name, presence: true, length: {maximum: 50}
  validates :player_num, presence: true,
                         numericality: {only_integer: true, greater_than_or_equal_to: 5, less_than_or_equal_to: 16}
  validate :player_num_must_be_greater_than_current_num, on: :update
  validates :day, presence: true
  validates :discussion_time, presence: true,
                              numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1440}
  validates :status, presence: true
  validates :access_password, length: {maximum: 20}, if: :access_password

  def assign_role
    roles = Settings.role_list[player_num].shuffle
    players.each do |p|
      r = roles.pop
      p.update(role: r)
    end
  end

  def lynch
    voted_players =
      if vote_target_players.present?
        vote_target_players
      else
        players.alive
      end
    excluded_player = exclude(voted_players)
    result_of_today.update!(voted_player: excluded_player)
  end

  def attack
    attacked_player = attack_target_player || players.alive.select(&:human?).sample
    return if attacked_player == guard_target_player || attacked_player.dead?
    attacked_player.update!(status: 'dead')
    result_of_today.update!(attacked_player: attacked_player)
  end

  def judge_end
    human_count = players.alive.select(&:human?).count
    wolf_count = players.alive.werewolf.count

    if human_count <= wolf_count
      :werewolf_win
    elsif wolf_count.zero?
      :human_win
    else
      :continued
    end
  end

  def player_from_user(user)
    return unless user
    players.includes(:user).find { |p| p.user == user }
  end

  def make_player_exit(user)
    player = players.find_by(user: user)
    player.update!(village_id: 0)
    player
  end

  def kick_player(player)
    make_player_exit(player.user)
    blacklist_users.create!(user: player.user)
  end

  def update_to_next_day
    update!(day: day + 1, next_update_time: Time.now + discussion_time.minutes)
    ProceedVillageJob.set(wait: discussion_time.minutes).perform_later(self)
    prepare_records
    prepare_result
  end

  def update_results
    update_divined_player_of_result
    update_guarded_player_of_result
  end

  def room_for_all
    rooms.for_all.first
  end

  def room_for_wolf
    rooms.for_wolf.first
  end

  def room_for_dead
    rooms.for_dead.first
  end

  def record_from_user(user)
    records.where(player: player_from_user(user), day: day).first
  end

  # Return remaining time by seconds
  def remaining_time
    time = (next_update_time - Time.now).to_i
    time > 0 ? time : 0
  end

  def divine_results
    results.pluck(:divined_player_id).compact.each_with_object({}) do |id, hash|
      hash[Player.find(id).username] = Player.find(id).human?
    end
  end

  def vote_results
    results.pluck(:voted_player_id).compact.each_with_object({}) do |id, hash|
      hash[Player.find(id).username] = Player.find(id).human?
    end
  end

  def result_of_today
    results.find_by(day: day)
  end

  def post_system_message(content)
    room_for_all.posts.create!(content: content, day: day, owner: :system)
  end

  def post_system_message_for_wolf(content)
    room_for_wolf.posts.create!(content: content, day: day, owner: :system)
  end

  def number_of_votes
    count_by_username(vote_target_players)
  end

  def start!
    return unless not_started?
    assign_role
    update_to_next_day
    update!(status: :in_play)
  end

  private

  def vote_target_players
    records_of_today.includes(:vote_target).map(&:vote_target).compact
  end

  def attack_target_player
    records_of_today.where.not(attack_target_id: nil).order("updated_at DESC").first&.attack_target
  end

  def guard_target_player
    bodyguard = players.alive.bodyguard.first
    return nil unless bodyguard
    records_of_today.find_by(player: bodyguard).guard_target
  end

  def exclude(target_players)
    counts = count_by_id(target_players)
    max = counts.values.max
    # if there are multiple players who are voted maximum number, choose one player randomly
    excluded_player = Player.find(player_ids_of_max_number(counts, max).sample)
    excluded_player.update!(status: 'dead')
    excluded_player
  end

  def count_by_id(target_players)
    target_players.each_with_object(Hash.new(0)) do |player, hash|
      hash[player.id] += 1
    end
  end

  def count_by_username(target_players)
    target_players.each_with_object(Hash.new(0)) do |player, hash|
      hash[player.username] += 1
    end
  end

  def player_ids_of_max_number(counts, max)
    counts.map do |id, count|
      id if count == max
    end.compact
  end

  def create_rooms
    rooms.create!(room_type: :for_all)
    rooms.create!(room_type: :for_wolf)
    rooms.create!(room_type: :for_dead)
  end

  def player_num_must_be_greater_than_current_num
    errors.add(:player_num, "は現在のプレイヤー数(#{players.count})以上に設定してください") if player_num < players.count
  end

  def prepare_records
    players.alive.each do |p|
      records.create!(player: p, day: day)
    end
  end

  def prepare_result
    results.create!(day: day)
  end

  def records_of_today
    records.where(day: day)
  end

  def update_divined_player_of_result
    return unless players.alive.fortune_teller.present?
    divine_target = records_of_today.find_by(player: players.fortune_teller.first).divine_target
    result_of_today.update!(divined_player: divine_target)
  end

  def update_guarded_player_of_result
    return unless players.alive.bodyguard.present?
    guard_target = records_of_today.find_by(player: players.bodyguard.first).guard_target
    result_of_today.update(guarded_player: guard_target)
  end
end

app/controllers/api/v1/villages_controller.rb
class Api::V1::VillagesController < Api::V1::ApiController
  skip_before_action :authenticate_user!, only: :remaining_time
  before_action :set_village

  def remaining_time
    render json: {remaining_time: @village.remaining_time}, status: 200
  end

  def divine
    render json: {messages: view_context.messages_of_result(@village.divine_results)}, status: 200
  end

  def see_soul
    render json: {messages: view_context.messages_of_result(@village.vote_results)}, status: 200
  end

  private

  def set_village
    @village = Village.find(params[:id])
    authorize @village
  end
end

app/controllers/villages/kicks_controller.rb
class Villages::KicksController < ApplicationController
  include VillagesHelper

  before_action :set_village, only: %i[edit update]

  def edit
  end

  def update
    player = @village.players.find_by(id: player_params[:id])
    if player
      @village.kick_player(player)
      @village.post_system_message(kick_message(player))
      ReloadBroadcastJob.perform_later(@village)
      redirect_to village_room_path(@village, @village.room_for_all), notice: "#{player.username} をキックしました"
    else
      redirect_to edit_village_kick_path(@village), notice: "プレイヤーが選択されていません"
    end
  end

  private

  def set_village
    @village = Village.find(params[:village_id])
    authorize @village, :kick?
  end

  def player_params
    params.require(:player).permit(:id)
  end
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  include VillagesHelper

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_village, only: %i[show edit update destroy start ruin]
  before_action :authorize_village, only: %i[index new create]

  def index
    villages =
      if params[:filter] == "ended"
        @filter = "ended"
        Village.where(status: %w[ended ruined])
      else
        Village.where(status: %w[not_started in_play])
      end
    @villages = villages.order("updated_at DESC").page params[:page]
    ActiveRecord::Precounter.new(@villages).precount(:players)
  end

  def show
  end

  def new
    @village = Village.new
  end

  def edit
  end

  def create
    @village = current_user.villages.new(village_params)

    if @village.save
      # TweetVillageJob.perform_later(@village)
      redirect_to villages_path, notice: "#{@village.name} が作成されました"
    else
      render :new
    end
  end

  def update
    if @village.update(village_params)
      @village.post_system_message(update_message(@village))
      redirect_to village_path(@village), notice: "#{@village.name} が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @village.destroy
    redirect_to villages_url, notice: "#{@village.name} が削除されました"
  end

  def ruin
    if @village.update(status: :ruined)
      @village.post_system_message(ruin_message(@village))
      ReloadBroadcastJob.perform_later(@village)
      redirect_to village_path(@village), notice: "#{@village.name} が廃村になりました"
    else
      render :edit
    end
  end

  def start
    @village.with_lock do
      @village.start!
    end
    @village.post_system_message(start_message(@village))
    ReloadBroadcastJob.perform_later(@village)
    redirect_to village_room_path(@village, @village.room_for_all), notice: "#{@village.name} を開始しました"
  end

  private

  def set_village
    @village = Village.find(params[:id])
    authorize @village
  end

  def authorize_village
    authorize Village
  end

  def village_params
    params.require(:village).permit(
      :name, :player_num, :discussion_time, :start_at,
      :show_vote_target, :access_password
    )
  end
end

app/helpers/villages_helper.rb
module VillagesHelper
  def datetime_display(start_at)
    if start_at
      start_at.strftime('%-m/%-d %H:%M')
    else
      '-'
    end
  end

  def link_to_profile(player)
    return "-" unless player.user
    link_to(player.user.username, users_profile_path(player.user.profile), target: "_blank")
  end

  def messages_of_result(results)
    return [] unless results
    messages = []
    results.each do |k, v|
      messages << "#{k}は#{human_or_werewolf(v)}です"
    end
    messages
  end

  def join_message(village, player)
    "#{village.players.count}人目、#{player.username}が参加しました"
  end

  def exit_message(player)
    "#{player.username}が退出しました"
  end

  def kick_message(player)
    "#{player.username}がキックされました"
  end

  def update_message(village)
    message = "作成者により村が更新されました\n"
    add_village_settings(village, message)
  end

  def add_village_settings(village, message)
    message << "村名: #{village.name}\n"
    message << "人数: #{village.player_num} 人\n"
    message << "議論時間: #{village.discussion_time} 分\n"
    message << "投票先の開示: #{I18n.t("activerecord.attributes.village.show_vote_target_value.#{village.show_vote_target}")}\n"
    message << "開始予定: #{datetime_display(village.start_at)}\n"
  end

  def ruin_message(village)
    "#{village.name}は廃村になりました"
  end

  def ready_to_start_message
    "全ての村人が集まりました\n作成者は「ゲーム開始」を押してください"
  end

  def start_message(village)
    message = ""
    add_village_settings(village, message)
    message << "この中には"
    Player.roles.keys.each do |role|
      count = role_count(village, role)
      next if count == 0
      message << "、#{I18n.t("activerecord.attributes.player.role_enums.#{role}")}が#{count}名"
    end
    message << "います\n"
    message << "それでは今から、人狼を見つけるために話し合ってください"
  end

  def noon_message(village)
    message = ""
    if village.show_vote_target
      add_vote_target(village, message)
    else
      add_the_number_of_votes(village, message)
    end
    message << "投票の結果、#{village.result_of_today.voted_player.username}は処刑された"
  end

  def add_vote_target(village, message)
    village.records.where(day: village.day).includes(:player).each do |record|
      if record.vote_target
        message << "#{record.player.username}は #{record.vote_target.username} に投票した\n"
      else
        message << "#{record.player.username}は投票しなかった\n"
      end
    end
  end

  def add_the_number_of_votes(village, message)
    village.number_of_votes.each do |username, count|
      message << "#{username}は #{count}票だった\n"
    end
  end

  def night_message(village)
    message = "夜が明けた\n"
    if village.result_of_today.attacked_player
      message << "昨晩の犠牲者は #{village.result_of_today.attacked_player.username} だった"
    else
      message << "昨晩は犠牲者がいなかったようだ"
    end
  end

  def morning_message(village)
    message = "現在の生存者は"
    village.players.alive.each do |player|
      message << "、#{player.username}"
    end
    message << "の#{village.players.alive.count}名だ"
  end

  def end_message(village)
    message = ""
    if village.werewolf_win?
      message << "もう人狼に抵抗できるほど村人は残っていない\n"
      message << "人狼は残った村人を全て食らい、村を去っていった"
    elsif village.human_win?
      message << "全ての人狼は息絶えた\n"
      message << "村人は人狼との戦いに勝利したのだ"
    end
  end

  def reveal_message(village)
    message = "プレイヤーの役職は以下の通りでした\n"
    village.players.each do |player|
      message << "#{player.username} : #{I18n.t("activerecord.attributes.player.role_enums.#{player.role}")}\n"
    end
    message
  end

  private

  def human_or_werewolf(bool)
    return "人間" if bool
    "人狼"
  end

  def role_count(village, role)
    Settings.role_list[village.player_num].count(role)
  end
end

app/views/villages/_form.html.slim
= form_for @village do |f|
  - if @village.errors.any?
    .alert.alert-danger
      ul
        - @village.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :player_num, "人数 (5~16人)"
    = f.number_field :player_num, class: 'form-control'
  .form-group
    = f.label :discussion_time, "議論時間 (1~1440分)"
    = f.number_field :discussion_time, class: 'form-control'
  .form-group
    = f.label :show_vote_target, class: 'control-label'
    div
      label.radio-inline
        = f.radio_button :show_vote_target, true, checked: @village.show_vote_target
        = t("activerecord.attributes.village.show_vote_target_value.true")
      label.radio-inline
        = f.radio_button :show_vote_target, false, checked: !@village.show_vote_target
        = t("activerecord.attributes.village.show_vote_target_value.false")
  .form-group
    = f.label :start_at
    br
    = f.datetime_select(:start_at,
      {discard_year: true, use_two_digit_numbers: true, minute_step: 10,
       date_separator: ' / ', datetime_separator: ' - ', time_separator: ' : '},
      {class: 'datetime-select form-control'})
  .form-group
    = f.label :access_password
    = f.text_field :access_password, class: 'form-control'
    p ※設定しない場合は未入力
  br

  - if @village.persisted?
    .button-inline
      = link_to "戻る", village_path(@village), class: 'btn btn-default'
      = f.submit "更新", class: 'btn btn-primary'
  - else
    .actions = f.submit "作成", class: 'btn btn-primary'

app/views/villages/edit.html.slim
h1 = "#{@village.name} を編集"

== render 'form'

app/views/villages/index.html.slim
- @page_title = '村を探す'
.village-header
  - if policy(Village).create?
    .pull-right.create-village-button
      = button_to "新規作成", new_village_path, method: :get, class: 'btn btn-sm btn-primary'
  h1 村を探す

table class="table table-striped table-villages"
  thead
    tr
      th 村名
      th 人数
      th 議論
      th 状態
      th 開始予定

  tbody
    - @villages.each do |village|
      tr
        td
          - if village.access_password.present?
            i.fa.fa-key.village-name-icon
          = link_to village.name, village_room_path(village, village.room_for_all), data: {turbolinks: "false"}
        td = "#{village.players_count} / #{village.player_num} 人"
        td = "#{village.discussion_time} 分"
        td = t("activerecord.attributes.village.status.#{village.status}")
        td = datetime_display(village.start_at)
= paginate @villages
br
- if @filter == "ended"
  = link_to("募集中/進行中の村を表示", villages_path)
- else
  = link_to("終了/廃村の村を表示", villages_path(filter: "ended"))
br

app/views/villages/new.html.slim
h1 新しい村を作成

== render 'form'

app/views/villages/show.html.slim
h1 = "#{@village.name} の詳細"

table class="table table-striped table-village-show"
  thead
    tr
      th.col-md-4 項目
      th.col-md-8 設定

  tbody
    tr
      td = t("activerecord.attributes.village.name")
      td = @village.name
    tr
      td = t("activerecord.attributes.village.player_num")
      td = "#{@village.players.count} / #{@village.player_num} 人"
    tr
      td = t("activerecord.attributes.village.discussion_time")
      td = "#{@village.discussion_time} 分"
    tr
      td = "状態"
      td = t("activerecord.attributes.village.status.#{@village.status}")
    tr
      td = t("activerecord.attributes.village.show_vote_target")
      td = t("activerecord.attributes.village.show_vote_target_value.#{@village.show_vote_target}")
    tr
      td = t("activerecord.attributes.village.start_at")
      td = datetime_display(@village.start_at)
    tr
      td = t("activerecord.attributes.village.access_password")
      td = @village.access_password.present? ? "あり" : "なし"

h4 参加者一覧
table class="table table-striped table-village-show"
  thead
    tr
      th プレイヤー
      th 状態
      - if @village.ended?
        th 役職
        th プロフィール
  tbody
    - players = @village.ended? ? @village.players.includes(user: :profile) : @village.players
    - players.each do |player|
      tr
        td = player.username
        td = player.alive? ? "生存" : "死亡"
        - if @village.ended?
          td = I18n.t("activerecord.attributes.player.role_enums.#{player.role}")
          td = link_to_profile(player)

.button-inline
  = link_to "戻る", village_room_path(@village, @village.room_for_all), class: 'btn btn-default'
  - if policy(@village).update?
    = link_to "編集", edit_village_path(@village), class: 'btn btn-primary'
- if policy(@village).ruin?
  br
  = button_to '廃村にする', ruin_village_path(@village), method: :get, data: { confirm: '本当に廃村にしますか？' }, class: 'btn btn-sm btn-danger'
  br
- if policy(@village).destroy?
  = button_to '削除', @village, method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-danger'