config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#welcome'

  devise_for :users, controllers: {registrations: 'registrations'}
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :users do
    resource :avatar, only: %i[edit update]
    resources :profiles, only: %i[show edit update]
  end

  resources :villages do
    member do
      get 'start'
      get 'ruin'
    end
    resource :kick, only: %i[edit update], module: "villages"
    resources :rooms, only: [:show]
  end
  namespace :api, format: 'json' do
    namespace :v1 do
      resources :records, only: [:show] do
        member do
          put 'vote'
          put 'attack'
          put 'divine'
          put 'guard'
        end
      end
      resources :villages, only: [:show] do
        member do
          get 'remaining_time'
          get 'divine'
          get 'see_soul'
        end
      end
      resources :rooms, only: [:show] do
        member do
          get 'posts'
          get 'all_posts'
        end
      end
    end
  end

  resources :notifications
  resources :manuals, only: %i[show new edit create update destroy]
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['AWS_BUCKET']}/sitemaps/sitemap.xml.gz")

  resources :players, only: %i[new edit create update destroy] do
    resource :avatar, only: %i[edit update], module: "players"
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  village_id :integer          not null
#  role       :integer          default("villager"), not null
#  status     :integer          default("alive"), not null
#  username   :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Player < ApplicationRecord
  after_update_commit :upload_variant_avatar

  attr_accessor :access_password

  enum role: {
    villager: 0,
    werewolf: 1,
    fortune_teller: 2,
    psychic: 3,
    bodyguard: 4,
    madman: 5
  }

  enum status: {
    alive: 0,
    dead: 1
  }

  belongs_to :user
  belongs_to :village, optional: true
  has_many :posts
  has_many :records
  has_one_attached :avatar

  validates :username, presence: true, length: {in: 1..20}
  validate :username_must_be_unique_in_village
  validates :role, presence: true
  validates :status, presence: true
  validate :check_access_password, if: :need_access_password?, on: :create

  def self.human_side_roles
    %w[villager fortune_teller psychic bodyguard]
  end

  def self.werewolf_side_roles
    %w[werewolf madman]
  end

  def human?
    villager? || fortune_teller? || psychic? || bodyguard? || madman?
  end

  def avatar_image_src
    @avatar_image_src ||=
      # if blob is invalid for ImageMagick, ActiveStorage::InvariableError occurs in `avatar.variant`
      if avatar.attached?
        begin
          url_for(avatar.variant(resize: "100x100"))
        rescue ActiveStorage::InvariableError
          nil
        end
      elsif user && user.avatar.attached?
        begin
          url_for(user.avatar.variant(resize: "100x100"))
        rescue ActiveStorage::InvariableError
          nil
        end
      else
        nil
      end
  end

  def exit_from_village
    update!(village_id: 0)
  end

  def need_access_password?
    village.access_password.present?
  end

  private

  def url_for(image)
    routes = Rails.application.routes
    routes.default_url_options = {host: Settings.host_name, protocol: protocol_option}
    routes.url_helpers.url_for(image)
  end

  def protocol_option
    if Rails.env.production?
      'https'
    else
      'http'
    end
  end

  def username_must_be_unique_in_village
    # Don't check a player to exit
    return if village_id == 0
    return unless village.players.where(username: username).where.not(id: id).present?
    errors.add(:base, "村内で同一ユーザーネームのプレイヤーが存在します")
  end

  def upload_variant_avatar
    return unless avatar.attached?
    UploadVariantAvatarJob.perform_later(self)
  end

  def check_access_password
    return if access_password == village.access_password
    errors.add(:base, "アクセスコードが誤っています")
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  include VillagesHelper

  before_action :set_player, only: %i[edit update destroy]
  before_action :authorize_village, only: %i[new create]

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = current_user.players.new(player_params)

    if @player.save
      @village = @player.village
      @village.post_system_message(join_message(@village, player))
      notify_ready_to_start if @village.players.count == @village.player_num
      redirect_to village_room_path(village, village.room_for_all), notice: "#{village.name} に参加しました"
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to village_room_path(@village, @village.room_for_all), notice: "#{@player.username} を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @player.update!(village_id: 0)
    @village.post_system_message(exit_message(player))
    redirect_to villages_path, notice: "#{@village.name} から退出しました"
  end

  private

  def set_player
    @player = Player.find(params[:id])
    @village = @player.village
    authorize @player
  end

  def authorize_player
    authorize Player
  end

  def player_params
    params.require(:player).permit(:village_id, :username)
  end

  def notify_ready_to_start
    @village.post_system_message(ready_to_start_message)
    ReloadBroadcastJob.perform_later(@village)
  end
end

app/controllers/players/avatars_controller.rb
class Players::AvatarsController < ApplicationController
  before_action :set_player, only: %i[edit update]
  before_action :check_params, only: :update

  def edit
  end

  def update
    @player.avatar.attach(params[:player][:avatar])
    redirect_to village_room_path(@village, @village.room_for_all), notice: "#{@player.username} を更新しました"
  end

  private

  def set_player
    @player = Player.find(params[:player_id])
    @village = @player.village
    authorize @player
  end

  def check_params
    return if params[:player][:avatar].present?
    @player.errors.add(:base, "プロフィール画像を選択してください")
    render :edit
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  include VillagesHelper

  before_action :set_player, only: %i[edit update destroy]

  def new
    @player = Player.new(village_id: params[:village_id], username: current_user.username)
    authorize @player
  end

  def edit
  end

  def create
    @player = current_user.players.new(player_params)
    authorize @player

    if @player.save
      @village = @player.village
      @village.post_system_message(join_message(@village, @player))
      notify_ready_to_start if @village.players.count == @village.player_num
      redirect_to village_room_path(@village, @village.room_for_all), notice: "#{@village.name} に参加しました"
    else
      render :new
    end
  end

  def update
    if @player.update(player_params)
      redirect_to village_room_path(@village, @village.room_for_all), notice: "#{@player.username} を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @player.exit_from_village
    @village.post_system_message(exit_message(@player))
    redirect_to villages_path, notice: "#{@village.name} から退出しました"
  end

  private

  def set_player
    @player = Player.find(params[:id])
    @village = @player.village
    authorize @player
  end

  def player_params
    params.require(:player).permit(:village_id, :username, :access_password)
  end

  def notify_ready_to_start
    @village.post_system_message(ready_to_start_message)
    ReloadBroadcastJob.perform_later(@village)
  end
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/players/_form.html.slim
= form_for @player do |f|
  - if @player.errors.any?
    .alert.alert-danger
      ul
        - @player.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :village_id
  .form-group
    = f.label :username
    = f.text_field :username, autofocus: true, class: 'form-control'
  - if @player.persisted?
    label プロフィール画像
    br
    = link_to "プロフィール画像の設定", edit_player_avatar_path(@player), class: 'btn btn-default'
    br
  - if @player.new_record? && @player.need_access_password?
    .form-group
      = f.label :access_password
      = f.text_field :access_password, class: 'form-control'
  br

  - if @player.persisted?
    .button-inline
      = link_to "戻る", village_room_path(@player.village, @player.village.room_for_all), class: 'btn btn-default'
      = f.submit "更新", class: 'btn btn-primary'
  - else
    .button-inline
      = link_to "戻る", village_room_path(@player.village, @player.village.room_for_all), class: 'btn btn-default'
      = f.submit "村に入る", class: 'btn btn-primary'
- if @player.persisted?
  br
  = button_to '村から出る', @player, method: :delete, data: { confirm: '本当に退出しますか？' }, class: 'btn btn-sm btn-danger'

app/views/players/edit.html.slim
h1 = "#{@player.username} を編集"

== render 'form'

app/views/players/edit_avatar.html.slim
h1 = "プロフィール画像の設定"
= form_for @player do |f|
  - if @player.errors.any?
    .alert.alert-danger
      ul
        - @player.errors.full_messages.each do |message|
          li = message
  p
    | 村専用のプロフィール画像を設定することができます
    br
    | 設定しない場合は、アカウントのプロフィール画像が使用されます
  .form-group
    = f.label :avatar
    - if @player.avatar.attached?
      .avatar-form
        = image_tag url_for(@player.avatar.variant(resize: "100x100"))
    = f.file_field :avatar, accept: 'image/jpeg,image/png', direct_upload: true
  br

  .button-inline
    = link_to "戻る", edit_player_path(@player), class: 'btn btn-default'
    = f.submit "更新", class: 'btn btn-primary'

app/views/players/new.html.slim
h1 村に入る

== render 'form'