config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#welcome'

  devise_for :users, controllers: {registrations: 'registrations'}
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :users do
    resource :avatar, only: %i[edit update]
    resources :profiles, only: %i[show edit update]
  end

  resources :villages do
    member do
      get 'start'
      get 'ruin'
    end
    resource :kick, only: %i[edit update], module: "villages"
    resources :rooms, only: [:show]
  end
  namespace :api, format: 'json' do
    namespace :v1 do
      resources :records, only: [:show] do
        member do
          put 'vote'
          put 'attack'
          put 'divine'
          put 'guard'
        end
      end
      resources :villages, only: [:show] do
        member do
          get 'remaining_time'
          get 'divine'
          get 'see_soul'
        end
      end
      resources :rooms, only: [:show] do
        member do
          get 'posts'
          get 'all_posts'
        end
      end
    end
  end

  resources :notifications
  resources :manuals, only: %i[show new edit create update destroy]
  get 'sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['AWS_BUCKET']}/sitemaps/sitemap.xml.gz")

  resources :players, only: %i[new edit create update destroy] do
    resource :avatar, only: %i[edit update], module: "players"
  end
end

app/views/layouts/_content.html.slim
.container.max-height[class="#{'room-container' if controller_name == 'rooms'}"]
  - if notice
    .alert.alert-success
      button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"] &times;
      = notice
  - if alert
    .alert.alert-danger
      button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"] &times;
      = alert
  = yield

app/views/layouts/_header.html.slim
.navbar-header
  button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
    span class="sr-only"
      | Toggle navigation
    span class="icon-bar"
    span class="icon-bar"
    span class="icon-bar"
  a.navbar-brand.navbar-title[href="#{root_path}"]
    = image_tag('logo.png', class: 'logo')
    | Jinro Lite
#navbar class="collapse navbar-collapse navbar-collapse-#{@color_of_navbar}" aria-expanded="false"
  ul class="nav navbar-nav"
    - if controller_name == 'rooms'
      - if policy(Player.new(village: @village)).create?
        li = link_to '村に入る', new_player_path(village_id: @village.id), data: {turbolinks: "false"}
      - if @village.player_from_user(current_user) && policy(@village.player_from_user(current_user)).update?
        li = link_to 'プレイヤーの編集', edit_player_path(@village.player_from_user(current_user)), data: {turbolinks: "false"}
      - if policy(@village).start?
        li = link_to 'ゲーム開始', start_village_path(@village), data: {turbolinks: "false"}
      - if @room.for_all? && policy(@village.room_for_wolf).show?
        li = link_to '人狼ルームへ', village_room_path(@village, @village.room_for_wolf), data: {turbolinks: "false"}, target: '_blank'
      - if @room.for_all? && @village.room_for_dead.present? && policy(@village.room_for_dead).show?
        li = link_to '墓場へ', village_room_path(@village, @village.room_for_dead), data: {turbolinks: "false"}, target: '_blank'
      - if policy(@village).show?
        li = link_to '村の詳細', village_path(@village), data: {turbolinks: "false"}
      - if policy(@village).kick?
        li = link_to 'プレイヤーのキック', edit_village_kick_path(@village), data: {turbolinks: "false"}
    - else
      li
        a[href="#{villages_path}"]
          i.fa.fa-search.navbar-icon
          | 村を探す
      li
        a[href="#{notifications_path}"]
          i.fa.fa-bell.navbar-icon
          | お知らせ
      - if Manual.count > 0
        li
          a[href="#{manual_path(Manual.first)}"]
            i.fa.fa-book.navbar-icon
            | マニュアル
      - elsif user_signed_in? && policy(Manual).create?
        li
          a[href="#{new_manual_path}"]
            i.fa.fa-book.navbar-icon
            | マニュアルを作成
      - if user_signed_in?
        li
          a[href="#{users_profile_path(current_user.profile)}"]
            i.fa.fa-user-circle-o.navbar-icon
            | プロフィール
        li
          a[href="#{edit_user_registration_path}"]
            i.fa.fa-gear.navbar-icon
            | 設定変更
        li
          a[href="#{destroy_user_session_path}" data-method="delete"]
            i.fa.fa-sign-out.navbar-icon
            | ログアウト
      - else
        li
          a[href="#{new_user_session_path}"]
            i.fa.fa-sign-in.navbar-icon
            | ログイン
        li
          a.registration[href="#{new_user_registration_path}"]
           .registration-button
             i.fa.fa-user-plus.navbar-icon
             | 新規登録

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title = page_title
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no"
    meta name="description" content="JinroLiteは人狼ゲームが無料で遊べるサービスです。シンプルな操作感なので初心者でも気軽に楽しむことができます。友達同士や見知らぬ人とオンラインで人狼を楽しみましょう。"
    meta property="og:type" content="website"
    meta property="og:title" content="#{page_title}"
    meta property="og:description" content="JinroLiteは人狼ゲームが無料で遊べるサービスです。シンプルな操作感なので初心者でも気軽に楽しむことができます。友達同士や見知らぬ人とオンラインで人狼を楽しみましょう。"
    meta property="og:image" content="https://www.jinro-lite.com/images/og_image.png"
    meta property="og:url" content="https://www.jinro-lite.com/"
    meta property="og:site_name" content="JinroLite"
    meta content="summary_large_image" name="twitter:card"
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('favicon.ico')
  body
    #app-root.wrapper.max-height
      nav class="navbar navbar-inverse navbar-fixed-top navbar-bg-#{@color_of_navbar}"
        .container
          = render partial: 'layouts/header'
      - if controller_name == 'welcome'
        = yield
      - else
        = render partial: 'layouts/content'
    - if controller_name == 'rooms' && action_name == 'show'
      javascript:
        var record = #{@record.to_json.html_safe}
        var villageId = #{@village.id}
        var villageStatus = "#{@village.status}"
        var roomId = #{@room.id}
      = javascript_pack_tag 'rooms/show'